### ISSUE TITLE
No suitable version installed

### ISSUE THREAD

**Issue by wilsonmar** [turnbullpress/tfb-code#4]
I'm at Terraform v0.10.6
Should I fall back to a previous version of Terraform or wait for updates to this?

**Comment by jamtur01** [comment]
Sorry - I am not sure I understand the issue? Can you elaborate please?

**Comment by wilsonmar** [comment]
My basic question is whether the current version 0.10.6 will work with the files in this repo.

Steps to reproduce on MacOS Sierra:
brew install -g terraform
terraform version >  v0.10.6
git clone https://github.com/turnbullpress/tfb-code 
cd tfb-code/2/base
terraform validate
Response:
<pre>
Error: 1 error(s) occurred:
* provider.aws: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
</pre>
I didn't change the key:
  access_key = "abc123"
  secret_key = "abc123"
  region     = "us-east-1"

**Comment by jamtur01** [comment]
You missed the 

`terraform init` command.

What version of the book do you have?

```
cd tfb-code/2/base
terraform validate
terraform init
```

**Comment by wilsonmar** [comment]
Well, that was a newbie mistake. transform init did the trick and terraform validate came back without issue. Thanks again.
