### ISSUE TITLE
Issue executing chapter3 Stack aws_elb.web: instances: should be a list (v0.10.7)

### ISSUE THREAD

**Issue by sensiblemedia** [turnbullpress/tfb-code#5]
Chapter 3 stack
Terraform v0.10.7
Cloned turnbullpress/tfb-code

```
# cd tfb-code/3/web
# terraform init
# terraform get
```
**Issue:**
Terraform validate / plan fails with the following error: 
```
# terraform validate 
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:
  * aws_elb.web: instances: should be a list 
```

**Code snippet:**
```
resource "aws_elb" "web" {
  name = "web-elb"

  subnets         = ["${module.vpc.public_subnet_id}"]
  security_groups = ["${aws_security_group.web_inbound_sg.id}"]

  listener {
    instance_port     = 80
    instance_protocol = "http"
    lb_port           = 80
    lb_protocol       = "http"
  }

  # The instances are registered automatically
  instances = "${aws_instance.web.*.id}"
}
```

**Fix:** 
`instances = ["${aws_instance.web.*.id}"]`

**Question:**
I appreciate the book specified v0.10.6 so has this issue arisen due to changes made in Terraform v0.10.7?

Really enjoying your book BTW :-)

**Comment by jamtur01** [comment]
Oh yes! I accidentally removed the list because the splat syntax changed. But yes - that should still be a list. Thanks!
